//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product1
    {
        public int Pid { get; set; }
        public string Ptitle { get; set; }
        public double Price { get; set; }
        public Nullable<int> id { get; set; }
    
        public virtual Category1 Category { get; set; }
    }
}
